4단계 - 세션 구현하기
next-step/jwp-was pull request #225
Opened 2022-06-29 13:06 UTC by ivvve

안녕하세요 세션 기능 구현하여 리뷰 요청드립니다 :)
기존에 우리가 프레임워크를 사용할 때 사용하는 방식과 동일한 인터페이스로 HttpRequest로부터 HttpSession을 가져다 쓸 수 있도록 해봤는데요.
그 과정에서 [Apache Tomcat 소스코드](https://github.com/apache/tomcat/blob/6916f850b0075513aea68b762d8aa530b3b5350b/java/org/apache/catalina/connector/Request.java#L2956)를 많이 참고하였고 지금과 같은 설계가 나왔습니다.

Request가 직접적으로 Response과 Session을 관리하는 객체를 의존하고 직접 사용하는 부분은 내부적으로 좋은 설계인가?라는 의문이 들면서도,
동시에 사용자 입장에서 사용하기 좋은 인터페이스를 제공하기 위해서 이런 식의 발상도 필요하겠구나라는 생각도 들었습니다.

그럼 리뷰 부탁드리겠습니다 :) 🙇‍♂️

2022-06-30 04:34 UTC, ghojeong requested changes
손영철님!
매우 깔끔하게 구현해주셨네요! 👍 
특히 기존의 구조가 매우 적극적으로 재활용된것 같아, 기존에 구조를 참 잘 설계하셨구나라고 느낍니다.

HttpRequest 에서 HttpResponse 에 대한 의존성이 생긴 듯하여,
이에 관한 영철님의 생각이 궁금하여 질문을 남겨보았습니다.
답변 남겨주시면, 바로 승인 후 머지하도록 하겠습니다.

2022-06-30 04:34 UTC, ghojeong commented on src/main/java/webserver/http/session/HttpSessionManager.java
> +    private final static Map<String, HttpSession> sessions = new HashMap<>();
저는 Container 라는 표현을 썼는데, 공식 문서를 보니 톰캣 코드를 보니 Manager 라는 표현이 나오는 군요.
저도 톰캣코드에 관심을 가지고 참고했으면 좋았을 텐데, 혼자서 구현부터 하려고 한 점은 스스로 반성하게 되네요.
참고하신 링크 알려주셔서 감사합니다!

2022-06-30 04:34 UTC, ghojeong commented on src/main/java/webserver/http/session/HttpSession.java
> +    }
invalidate 를 할 때 clear 를 하는 것만 생각했지,
SessionManager 에서 세션을 제거해 주어야 한다는 생각은 미처 하지 못했네요.
좋은 아이디어 얻고 갑니다. 👍

2022-06-30 04:34 UTC, ghojeong commented on src/main/java/webserver/http/request/HttpRequest.java
> +    private HttpResponse response;
이 주석은 무슨 의도로 남겨두신건가요?

2022-06-30 04:34 UTC, ghojeong commented on src/main/java/webserver/http/controller/utils/SessionUtils.java
> +}
static 메소드만 제공하는 유틸함수라면, 생성자를 private 으로 선언해주시면 좋을 것 같습니다.

궁금해서 여쭈어보는데, setUser 와 getUserOrNull 을 별도의 유틸로 분리하신 의도가 무엇인가요?
현제 controller 아래의 util 로 분류가 되어 있는데, SessionUtils 안에 있는 내용이 굉장히 user domain 과 연관성이 깊은 것 같다고 느껴져서 여쭈어보았습니다.

만약 user domain 과 크게 상관없는 SessionUtils 기능 모음을 만들고 싶었다면, session 패키지 아래에 util 을 만들거나,
아니면 아예 HttpSession 클래스에 메소드를 위치시켜도 되지 않나 라는 생각이 들어서요.

2022-06-30 04:34 UTC, ghojeong commented on src/main/java/webserver/http/request/HttpRequest.java
> +    }
세션을 생성한 후, 쿠키에 sessionId 를 저장하는 작업을 HttpRequest 클래스 작업을 하시는 군요.
음... 사실 저도 이 부분 때문에 고민을 굉장히 많이 했는데,
저는 이로 인해서 HttpRequest 와 HttpResponse 사이에 의존성이 생긴것 같아서,
3단계에서 의도한 리팩토링에 반하지 않나라는 생각이 들었습니다.

3단계 리팩토링의 핵심이 클라이언트의 요청과 응답을 분리해서 구현하기로 생각했어서요.
request 와 response 가 별개의 패키지로 나뉘어 있는데, 아쉽다는 생각이 들었습니다.

이건 제 개인적인 의견이므로 엄청 진지하게 생각하지 않으셔도 됩니다.
참고로 저도 비슷한 고민을 하다가, 저는 반대로 세션과 쿠키 사이에 의존성이 생겨버려서요.
혹시 이와 관련해서 좋은 생각이 있으신가 해서 여쭈어보았습니다.

2022-06-30 04:48 UTC, ghojeong commented on src/main/java/webserver/http/request/HttpRequest.java
> +    }
> Request가 직접적으로 Response과 Session을 관리하는 객체를 의존하고 직접 사용하는 부분은 내부적으로 좋은 설계인가?라는 의문이 들면서도,
> 동시에 사용자 입장에서 사용하기 좋은 인터페이스를 제공하기 위해서 이런 식의 발상도 필요하겠구나라는 생각도 들었습니다

참고로 프레임워크의 사용자 입장에서 사용하기 좋은 인터페이스라는 데는 저도 동의합니다.
저 같은 경우는 내부적으로 의존하지 않게하려다 보니, Controller 에서 세션과 쿠키의 설정을 직접해주어야 하는 불편함이 발생해서요.
프레임워크 개발자가 편하게 개발하다보면, 프레임워크의 사용자가 불편해지게 되는 것 같네요.

2022-06-30 06:14 UTC, ghojeong approved these changes
손영철님 덕분에 Apache Tomcat 소스코드를 자세히 읽고나서,
영철님의 구조가 납득되었습니다.
덕분에 많이 배웠네요. 머지하도록 하겠습니다.

2022-06-30 06:14 UTC, merged

2022-07-01 13:09 UTC, ivvve commented on src/main/java/webserver/http/controller/utils/SessionUtils.java
> +}
> static 메소드만 제공하는 유틸함수라면, 생성자를 private 으로 선언해주시면 좋을 것 같습니다.
아 넵넵 맞습니다!

잘 아는 개념이지만 개발하면서 자꾸만 깜빡하게 되는 부분이네요 🥲 

> 궁금해서 여쭈어보는데, setUser 와 getUserOrNull 을 별도의 유틸로 분리하신 의도가 무엇인가요?
현제 controller 아래의 util 로 분류가 되어 있는데, SessionUtils 안에 있는 내용이 굉장히 user domain 과 연관성이 깊은 것 같다고 느껴져서 여쭈어보았습니다.
>
> 만약 user domain 과 크게 상관없는 SessionUtils 기능 모음을 만들고 싶었다면, session 패키지 아래에 util 을 만들거나,
아니면 아예 HttpSession 클래스에 메소드를 위치시켜도 되지 않나 라는 생각이 들어서요.

웹과 관련된 기능은 되도록 Web framework로서 순수성을 갖게하고 싶어서 session은 User나 다른 controller에서 처리하는 기능을 넣지 않도록 설계하였습니다!

그리고 SessionUtils에 대한 의도는 User 도메인과 연관성 보다는 session attribute를 set하고 get할 때
key로써 사용되는 name과 저장되는 type을 일정하게 사용하기 위해서 Util을 만들었다고 생각해주시면 될 것 같습니다!
(아시다시피 HttpSession의 attribute는 너무 범용적이어서 값을 가져올 때 실수 좀 만하면(예를 들어 name에 오타를 낸다던가, 저장되는 값의 타입을 생각지도 않은 것을 넣는다던가) 오류가 날 소지가 있기 때문에...)

사실 webserver/http 패키지 밑에다가 전부 집어넣다보니 이러한 의도가 잘 드러나진 않았던 것 같네요 😿

2022-07-01 13:11 UTC, ivvve commented on src/main/java/webserver/http/request/HttpRequest.java
> +    private HttpResponse response;
톰캣 코드를 고대로 긁어왔는데, 해당 Request와 관련된 Response가 필드임을 나타내기 위해 주석을 사용했습니다.

2022-07-01 13:17 UTC, ivvve commented on src/main/java/webserver/http/request/HttpRequest.java
> +    }
오 넵넵 사실 톰캣 코드를 안봤으면 너무 클래스간 커플링이 생기는 방향이라 이렇게 코딩할 생각을 전혀하지 않았을 것 같아요 👀 
기회가 기회니까 이렇게도 코딩을 해봤는데 사용자를 위한 코드를 짜는 것에 대해 생각할 수 있었던 것 같습니다 ㅎㅎ