Step4 리뷰 요청 드립니다
next-step/jwp-was pull request #325
Opened 2022-08-02 15:53 UTC by itdar

안녕하세요 동철님!
머지 후에 바로 리뷰 요청드리려니 죄송스럽네요 ㅎㅎ;;
미리미리 꾸준히 했어야되는데 ㅠㅠ
리뷰 감사합니다!!

2022-08-03 14:57 UTC, sah3122 requested changes
세션 구현 잘해주셨습니다 👍 
몇가지 고민거리를 남겨두었는데 확인 부탁드려요 🙏 
DM은 언제나 환영이니 질문 많이 해주세요 😄

2022-08-03 14:57 UTC, sah3122 commented on src/main/java/webserver/domain/CustomSession.java
> +public abstract class CustomSession implements HttpSession {
HttpSession 인터페이스를 활용하기 보다는 자체적으로 구현해보는것이 어떨까요 ㅎㅎ 
제공하지 않은 메소드를 굳이 구현할 필요 없을것 같아요 !

2022-08-03 14:57 UTC, sah3122 commented on src/main/java/webserver/domain/Sessions.java
> +public enum Sessions {
enum을 활용한 싱글톤 구현이 인상적이네요 👍

2022-08-03 14:57 UTC, sah3122 commented on src/main/java/webserver/domain/Sessions.java
> +
현재 생성된 세션이 존재하는지, 존재한다면 해당 세션을 반환해야하지 않을까요 ?

2022-08-03 14:57 UTC, sah3122 commented on src/main/java/webserver/request/HttpRequest.java
> +    }
```suggestion
    public String getSessionId() {
        return this.cookies.get(HttpHeader.JSESSIONID);
    }
```
HttpReqeust 가 Cookies 객체를 가지고 있었다면 위와 같이 간단히 표현 가능했을것 같아요. 
쿠키 값을 얻기 위해 매번 Cookies.of() 와 같이 객체 생성을 하지 않아도 될것 같구요 ㅎㅎ

2022-08-03 14:57 UTC, sah3122 commented on src/main/java/webserver/servlet/UserLoginController.java
> +            httpResponse.addHeader(HttpHeader.SET_COOKIE, KEY_LOGINED + "=" + false + "; " + "Path=/");
```java
HttpResponse#addCookie(Cookie cookie)
```
위 메소드를 구현해보는건 어떨까요 >?

2022-08-03 14:57 UTC, sah3122 commented on src/main/java/webserver/servlet/UserLoginController.java
> +        httpResponse.addHeader(HttpHeader.SET_COOKIE, HttpHeader.JSESSIONID + "=" + session.getId());
현재는 세션을 사용하는 순간마다 Response Cookie에 JSESSIONID 값을 추가하기 위해 위와 같은 코드가 존재해야 할것 같아요. 
조금 어려운 질문이 될수도 있을것 같은데 효율적으로 처리할수 있는 방법을 고민해보세요 ㅎㅎ

2022-08-03 14:57 UTC, sah3122 commented on src/main/java/webserver/servlet/UserListController.java
> +        HttpSession session = Sessions.INSTANCE.get(sessionId);
```suggestion
        HttpSession session = httpRequest.getSession();
```
위와 같이 제공하지 않은 이유가 있을까요 ㅎㅎ

2022-08-03 15:57 UTC, itdar commented on src/main/java/webserver/domain/CustomSession.java
> +public abstract class CustomSession implements HttpSession {
옙 클래스 하나만 남기고 상위는 없애보겠습니다!!

2022-08-03 16:01 UTC, itdar commented on src/main/java/webserver/domain/Sessions.java
> +public enum Sessions {
이펙티브자바 3번쨰에 나왔던걸 보고 사용하기 간편한데 enum 특징이 싱글톤에 잘 맞는 것 같아서 싱글톤 구현 시에 사용하고 있습니다!!

2022-08-03 16:02 UTC, itdar commented on src/main/java/webserver/domain/Sessions.java
> +
엇 그러네요 ㅎㅎ; 수정해보겠습니다!

2022-08-03 16:32 UTC, itdar commented on src/main/java/webserver/request/HttpRequest.java
> +    }
아.. 만들면서도 쿠키를 Request 에 필드로 넣을까말까 필드가 너무 많지 않은가 했었는데요 ㅎㅎ;
필드로 넣는다면 그래도 쿠키는 Header 보다는 Request 에 넣어보겠습니다!!

2022-08-03 16:42 UTC, itdar commented on src/main/java/webserver/servlet/UserLoginController.java
> +            httpResponse.addHeader(HttpHeader.SET_COOKIE, KEY_LOGINED + "=" + false + "; " + "Path=/");
오 넵 추가해보겠습니다!~

2022-08-03 17:05 UTC, itdar commented on src/main/java/webserver/servlet/UserLoginController.java
> +        httpResponse.addHeader(HttpHeader.SET_COOKIE, HttpHeader.JSESSIONID + "=" + session.getId());
음..
```java
    @Override
    public void doPost(HttpRequest httpRequest, HttpResponse httpResponse) {
        String userId = httpRequest.getParameter("userId");
        String password = httpRequest.getParameter("password");
        validate(userId, password);

        User userFound = DataBase.findUserById(userId)
            .orElseThrow(() -> new IllegalStateException(NOT_FOUND_MEMBER));

        if (!userFound.fitPassword(password)) {
            httpResponse.addCookie(Cookie.logined(false, "/"));
            httpResponse.sendRedirect("/user/login_failed.html");
            return;
        }

        HttpSession session = httpRequest.getSession().login();
        httpResponse.addCookie(Cookie.jsseionId(session.getId()));
        httpResponse.sendRedirect("/index.html");
    }
```

이렇게 수정해보았습니다!!

2022-08-03 17:32 UTC, itdar commented on src/main/java/webserver/servlet/UserListController.java
> +        HttpSession session = Sessions.INSTANCE.get(sessionId);
Request 안에서 Sessions 싱글톤을 의존하는게 어색한가 싶었는데, 정리하고 보니 그렇지 않은 것 같네요 ㅎㅎ;;
부근을 같이 정리해보았습니다!!

2022-08-04 13:39 UTC, sah3122 approved these changes
피드백 반영 잘해주셨어요 👍 
간단한 코멘트 남겨두었는데 확인 부탁드리며 다음 미션도 화이팅입니다 !

2022-08-04 13:39 UTC, sah3122 commented on src/main/java/webserver/domain/Cookie.java
> +public class Cookie {
쿠키 정의 👍 
cookieString 을 세분화 하여 key / value / path 정도의 상태를 재 정의 하는것도 좋을것 같습니다 😄

2022-08-04 13:39 UTC, sah3122 commented on src/main/java/webserver/domain/Sessions.java
>          return this.sessions.get(sessionId);
세션을 가져오는 로직 리팩토링 👍 
sessions.get(sessionId) 값이 null 인 경우 처리도 들어가 있다면 더 안정성을 보장해줄수 있겠네요 !

2022-08-04 13:39 UTC, sah3122 commented on src/main/java/webserver/servlet/UserLoginController.java
> +        httpResponse.addCookie(session.getLoginedCookie());
```suggestion
        HttpSession session = httpRequest.getSession();
        session.add(key, value);
```
일반적으로 Session 을 사용하는 코드는 위와 같이 구현하는게 깔끔하다고 생각합니다. 
`httpResponse.addCookie(session.getLoginedCookie());` 와 같이 Response 에 SesseionId를 넣어주는것이 필요는 하지만, 개발자가 직접 다루기엔 휴면에러가 발생할 가능성이 너무 큰것 같아요. 

HttpRequest에서 Session을 가져올때  세션이 있다면, 기존 세션을 가져와야 하고, 없다면 새로 생성해주어야 합니다. 여기까지 구현은 잘해주셨어요 👍 
다음 스탭으로 Response 에 SessionId 를 실어주어야 하는데, Tomcat 에서 Session 구현을 위해 Response 객체를 어떻게 다루었는지 한번 보시면 좋을것 같아 링크 남겨드려요 ㅎㅎ 

https://github.com/apache/tomcat/blob/6916f850b0075513aea68b762d8aa530b3b5350b/java/org/apache/catalina/connector/Request.java#L677-L684

톰캣에서는 Request 객체가 Response 객체를 가지는 구조로 처리하였는데, 참고만 해주시면 될것 같습니다. ㅎㅎ 
저는 미션을 구현할때 ThreadLocal을 활용하여 Response 객체를 저장하고, Session 초기화시 응답 헤더에 추가해주는 방법으로 구현했던것 같아요 😄

2022-08-04 13:39 UTC, merged

2022-08-04 16:17 UTC, itdar commented on src/main/java/webserver/domain/Sessions.java
>          return this.sessions.get(sessionId);
오 입력만 처리를 해뒀네요 ㅎㅎ; 결과 null 처리를 해두겠습니다!

2022-08-04 16:25 UTC, itdar commented on src/main/java/webserver/domain/Cookie.java
> +public class Cookie {
아하.. 쿠키에 내용물 포맷에 대해서 자세히 안알아봐서 어떻게 정의할지를 몰랐네요..
확인해보고 재정의 해보겠습니다!@

2022-08-07 05:46 UTC, itdar commented on src/main/java/webserver/servlet/UserLoginController.java
> +        httpResponse.addCookie(session.getLoginedCookie());
오.. 읽어보고 읽은 내용이랑 동철님 방법이랑 참고해서 생각을 좀 해보고 적용을 해겠습니다!!