Step2 - HTTP 웹서버 구현
next-step/jwp-was pull request #326
Opened 2022-08-02 16:04 UTC by koola97620

안녕하세요 리뷰어님! 오랜만에 PR을 올리게 됐네요.
이번 과정 구현할 기능도 많았고 고려해야 할 것도 많아서 시간이 많이 걸렸습니다.
그래도 이번 step 을 진행하면서 http , 웹서버에 대해 찾아보고 공부할 수 있는 기회를 가지게 되어 많은 도움이 됐습니다 :)
피드백 부탁드립니다!!

2022-08-03 02:27 UTC, kang-hyungu requested changes
재용님 몇 가지 피드백 남겼습니다.
수정해보시고 리뷰 재요청주세요.

2022-08-03 02:27 UTC, kang-hyungu commented on src/main/java/controller/Controller.java
> +    boolean matchHttpMethodAndPath(HttpRequest request);
메서드명에 내부 로직을 상세히 적을 필요는 없어 보이네요.

```suggestion
    boolean match(HttpRequest request);
```

2022-08-03 02:27 UTC, kang-hyungu commented on src/main/java/controller/CreateUserController.java
> +        return HttpResponse.of(
이런 형태의 팩터리 메서드를 추가해보면 어떨까요

```suggestion
        return HttpResponse.ofFound("/index.html");
```

2022-08-03 02:27 UTC, kang-hyungu commented on src/main/java/controller/DispatchController.java
> +    private static Set<Controller> controllers;
```suggestion
    private static final Set<Controller> controllers;
```

2022-08-03 02:27 UTC, kang-hyungu commented on src/main/java/controller/DispatchController.java
> +        HttpResponse httpResponse = controllers.stream()
```suggestion
        return controllers.stream()
```

바로 리턴해도 되지 않을까요?

2022-08-03 02:27 UTC, kang-hyungu commented on src/main/java/controller/LoginController.java
> +                    ResponseHeader.of(Map.of(
응답 헤더를 생성하는 부분에서 중복이 보이는데 좀더 개선해볼 방법 없을까요

2022-08-03 02:27 UTC, kang-hyungu commented on src/main/java/controller/LoginController.java
> +        return request.getBodyValue("password").equals(user.getPassword());
패스워드가 맞는지 체크하는 부분은 비즈니스 로직으로 볼 수 있겠네요
user 객체에서 비밀번호 검증하도록 만드는게 어떨까요?

2022-08-03 02:27 UTC, kang-hyungu commented on src/main/java/controller/StaticController.java
> +                StaticController.class.getClassLoader().getResource(addStaticPath(request.getPath())) != null;
한줄에 다 쓰는 것보다 적절히 변수로 추출하면 유지보수할 때 코드 파악하기 좋을 것 같습니다.

2022-08-03 02:27 UTC, kang-hyungu commented on src/main/java/model/HttpRequest.java
> +import org.springframework.util.Assert;
스프링 프레임워크에 의존적인 Assert 대신에 Objects.requireNonNull()를 사용해보면 어떨까요

2022-08-03 02:27 UTC, kang-hyungu commented on src/main/java/model/HttpRequestBody.java
> +    public String getValue(String userId) {
http request body와 관련된 변수명으로 바꿔보면 어떨까요

2022-08-03 02:27 UTC, kang-hyungu commented on src/main/java/model/HttpRequestHeader.java
> +        return cookie != null && cookie.contains("logined=true");
쿠키와 관련된 로직은 쿠키 객체를 따로 추가하는게 좋겠네요
3단계 미션 진행하면서 적용해보시기 바랍니다.

2022-08-03 20:39 UTC, koola97620 commented on src/main/java/model/HttpRequestHeader.java
> +        return cookie != null && cookie.contains("logined=true");
넵! 3단계에서 변경해보겠습니다

2022-08-03 20:44 UTC, koola97620 commented
피드백 감사합니다!

2022-08-04 08:18 UTC, kang-hyungu approved these changes
재용님 피드백 반영 잘 해주셨습니다.
pr은 머지 처리하겠습니다. 다음 미션 진행해주세요.

2022-08-04 08:19 UTC, merged