Step3 리뷰 부탁드리겠습니다.
next-step/jwp-was pull request #360
Opened 2022-08-10 15:32 UTC by youngsuseo

안녕하세요!
step 3 HTTP 웹 서버 리팩토링 코드 리뷰 부탁드리겠습니다.
감사합니다!! 🙂

2022-08-12 13:29 UTC, ghojeong requested changes
서영수 님!
리팩토링 굉장히 잘해주셨습니다!
특히 테스트 코드는 가독성이 매우 좋아서 많은 칭찬을 드리고 싶네요. 👍 

설계상 궁금했던 부분들에 대해서 몇가지 질문을 남겨보았습니다.
꼭 전부 반영해주실 필요는 없고, 혹시 본인만의 합리적인 의견이 있으셨다면,
답변을 남겨주시는 것만으로도 충분합니다!

답변 남겨주시면 승인후 머지하겠습니다.

2022-08-12 13:29 UTC, ghojeong commented on README.md
> +         2. 변경된 요구사항에 따라 클래스 구조 재설계
어떻게 리팩토링을 하셨는지 자세히 적어주신점 좋습니다. 👍

2022-08-12 13:29 UTC, ghojeong commented on src/main/java/cookie/Cookie.java
>      }
현재 cookie 를 단순한 String 값으로만 관리하고 있는듯한데,
key-value 자료구조로 관리할 수 있도록 하면 어떨까요?
HTTP Response 할때는 toString 으로 String 값으로 변환할 수 있도록 하고요.

2022-08-12 13:29 UTC, ghojeong commented on src/main/java/webserver/controller/Controller.java
> +}
리팩토링의 핵심인 Controller 인터페이스와, AbstractController 추상클래스 매우 잘 구현해주셨습니다. 👍

2022-08-12 13:29 UTC, ghojeong commented on src/main/java/webserver/controller/AbstractController.java
> +    }
AbstractControlle 에서 doPost 와 doGet 을 abstract 로 선언하지 않고,
굳이 비어있는 void 함수로 정의하는 이유가 있나요?
이렇게 해버리면, doPost 와 doGet 을 override 하지 않는 자식 클래스가 생기더라도 IDE 에서 컴파일 에러를 표시해주지 않을 것 같아서요.

2022-08-12 13:29 UTC, ghojeong commented on src/main/java/webserver/controller/ControllerEnum.java
> +        }
벌써부터 Reflection 을 활용해주시다니 대단하군요! 👍
본래의 과제 의도는 reflection 사용 없이, 다형성을 잘 활용해서 로직의 분기가 일어나도록 하는 것이었지만,
이런 방식도 나쁘지는 않다고 생각합니다.

2022-08-12 13:29 UTC, ghojeong commented on src/main/java/webserver/controller/ListUserController.java
> +    }
ControllerEnum 에서 자칫하면 글로벌 메서드가 될수 있는 로직을 담당하고 있는 모습이 그리 좋아보이지 않습니다.
차라리 AuthService 처럼, 로그인 비즈니스 로직을 담당하는 서비스 계층을 하나 더 만드시는 것은 어떻게 생각하시나요?

2022-08-12 13:29 UTC, ghojeong commented on src/main/java/webserver/controller/UserController.java
>      }
현재 createUserGet 에서는 createUserPost 와 다르게 DataBase.addUser 를 하고 있지 않은듯 한데,
의도된 것인지 여쭈어봅니다.
DataBase 를 컨트롤러에서 직접 접근하기 보다는 UserService 계층을 하나 더 만드는 것에 대해서는 어떻게 생각하시나요?

2022-08-12 13:29 UTC, ghojeong commented on src/test/java/webserver/http/model/response/HttpResponseTest.java
> +    }
친절한 테스트 DisplayName 감사합니다.
어떤 요구사항을 테스트하려 한것인지 명확해서 읽기 편했습니다. 👍

2022-08-12 13:29 UTC, ghojeong commented on src/main/java/webserver/http/model/HandlerMapping.java
> +    }
ControllerEnum 을 예쁘게 정의해주셨는데,
controllerMap 에 하드 코딩으로 put 을 하는게 이상하다고 느껴졌습니다.
컨트롤러의 엔드포인트 관리를 한곳에서 하는게 협업할 때의 혼란을 예방할 수 있다고 생각하는데,
어떻게 생각하시나요?

2022-08-12 13:29 UTC, ghojeong commented on src/main/java/webserver/http/model/request/HttpRequest.java
> +    }
기본 생성자를 토대로 굉장히 예쁘게 정리해 주셨다고 생각합니다.
개인적으로 정적 팩토리를 여러개 정의하는 것보다,
제가 선호하는 취향저격 스타일인지라 언급해보았습니다. 👍

2022-08-12 13:29 UTC, ghojeong commented on src/main/java/webserver/http/model/response/HttpResponse.java
> +    }
HttpResponse 에서 forward, response200, sendRedirect 매우 훌륭하게 구현해주셨습니다!
한가지 궁금해져서 여쭈어봅니다.
[HTTP Status Code](https://developer.mozilla.org/ko/docs/Web/HTTP/Status) 는 굉장히 많은데,
만약 요구사항이 늘어나서 더 많은 HTTP Status 를 대응해야할 경우,
HttpResposne 에 별도의 메서드로 계속 정의를 할 것인지 설계가 궁금해서 여쭈어봅니다.

그럴 경우 HttpResponse 가 점점 두꺼워질 수도 있지 않을까 하는 생각이 들어서요.

2022-08-13 05:54 UTC, youngsuseo commented on src/main/java/cookie/Cookie.java
>      }
네, 기존 구조에서는 cookie 안 String 값에 logined=true 라는 키,값 형태의 값을 가지고 있었는데,
이를 키, 값을 가지는 자료 구조로 변경하는 것이 더 좋을 것 같습니다.
해당 내용으로 수정 완료하였습니다. 감사합니다!

2022-08-13 05:58 UTC, youngsuseo commented on src/main/java/webserver/controller/AbstractController.java
> +    }
처음에는 실제 구현체인 CreateUserController, ListUserController, LoginController 에서
doGet, doPost 메소드 전부를 사용하지 않고 하나의 메소드만 사용하는 것 같아,
abstract 클래스에서 해당 내용을 구현하여, 실제 구현 클래스에게 메소드 사용을 강제 하지 않으려고 했는데,
그것보다 하위 실제 구현 클래스에서 사용하게 하는 것이 맞는 것 같습니다.

혹시, ListUserController에서 doPost() 메소드 같은 경우 메소드 내부에서 아무런 구현이 없는데,
이렇게 두어도 괜찮을까요?
아니면 방어코드로 예외를 발생시켜 사용할 수 없는 메소드라는 것을 명시해두는 게 좋을까요??

2022-08-13 06:00 UTC, youngsuseo commented on src/main/java/webserver/controller/UserController.java
>      }
네 service 계층을 하나 더 만드는 것이 좋을 것 같습니다! 😃

2022-08-13 06:05 UTC, youngsuseo commented on src/main/java/webserver/http/model/HandlerMapping.java
> +    }
최초에 step1에서 Controller enum을 만들고,
step2 에서는 controllerEnum을 사용하지 않고 아얘 새로운 HandlerMapping을 만들게 되었었습니다. 제가 따로 표시를 하지 않아 헷갈리게 해드린 것 같아 죄송합니다 😢 

그런데 말씀해주신 것을 듣고 보니, HandlerMapping은 framework에 속한 클래스이고, controller enum은 백엔드에서 사용하는 (설정하는) 클래스인 것 같아서 두개를 둘 다 사용하는 구조로 변경하였습니다!
엔드포인트는 ControllerEnum에서 관리하지만 다형성을 통해 controller 주입은 handlerMapping 클래스에서 주입하게 구조를 변경하였습니다. 
handlerMapping은 프레임워크 내부 클래스고, controllerEnum은 백엔드 개발에 부분이라고 생각해도 괜찮을까요?

2022-08-13 06:13 UTC, youngsuseo commented on src/main/java/webserver/http/model/response/HttpResponse.java
> +    }
httpResponse 내부에 responseHeader(StatusCode statusCode, ContentType contentType, int lengthOfBodyContent) 메소드를 추가하여 입력되는 값에 따라 응답헤더를 만들 수 있도록 구현하였는데,

해당 메소드 내부에서는 responseHeaders.getResponseHeaderMap().put() 의 형태로 Content-Type, Content-Length만 넣어주고 있도록 구현이 되었습니다.

만약 responseHeaderMap에 더 많은 정보를 담아야 하거나, 다른 정보를 담고 싶은 경우가 생길 것을 대비해서 responseHeaderMap 에 데이터를 입력하는 부분은 해당 메소드를 사용하는 쪽에서 입력할 수 있도록 설정하는 것이 좋을까요?

2022-08-13 07:24 UTC, youngsuseo commented on src/main/java/webserver/http/model/response/ContentType.java
> +
ContentType enum은 Extension enum 클래스와 비슷한 enum을 가지고 있는데,
실질적으로 사용하는 역할이 다른 것 같아 분리를 하여 구현하게 되었습니다.

비슷한 enum을 가지는 클래스에서 역할이 다르다고 생각하면 따로 클래스를 분리해서 만드는게 좋을까요?

2022-08-13 10:33 UTC, ghojeong commented on src/main/java/webserver/controller/AbstractController.java
> +    }
저같은 경우 ListUserController 에서 또한 강제로 구현이 필요하도록 하고,
커스텀 예외를 만들어서 throw Exception 을 하는 방식을 선호합니다.

2022-08-13 10:36 UTC, ghojeong commented on src/main/java/webserver/http/model/HandlerMapping.java
> +    }
제가 영수님 코드를 읽고 느끼기에는, 백엔드 개발자가 작성하도록 요구되는 영역이 ControllerEnum 이라고 느껴졌었습니다.
꼭 ControllerEnum 이 아니라, HandlerMapping 에서 작성해야한다고 하더라도,
둘 중에 하나의 클래스로 통일하는 편이 백엔드 개발자와 프레임워크 개발자간의 소통 불화를 방지할 수 있다고 생각했습니다.

결국 드리고 싶었던 피드백은 "객체의 책임을 명확히 하자" 입니다.
SRP 원칙에서, 한 객체가 한 가지 책임을 지는 것을 강조하는 것처럼,
한 가지 책임 또한 담당하는 객체가 하나인 구조를 저는 선호하는 편입니다.

2022-08-13 10:40 UTC, ghojeong commented on src/main/java/webserver/http/model/response/HttpResponse.java
> +    }
지금은 말씀주신 responseHeader 만으로도 충분히 유연한 구조라고 생각합니다.
꼭 수정을 요청하기 보다는, 생각해볼만한 포인트 같아서 언급을 해보았습니다.
저는 개발을 할 때, 나중에 제 코드가 다른 사람과 새로운 요구사항에 부딪혔을 때도 계속 재사용 될수 있는 구조인지 생각을 해보고는 하는데,

제가 영수님 동료의 입장에서 영수님의 코드를 넘겨받았을 때, 어떻게 추가 기능을 구현할지 영수님께 물어볼만한 내용을 피드백 드렸습니다.
그럴 때는 지금처럼 HttpResponse 가 두꺼워지는게 걱정된다면, 지금처럼 responseHeader 를 직접 사용해보시라고 설명하는 것으로 충분하다고 생각합니다.
만약 영수님이 퇴사를 할 경우에는 해당 부분에 대한 문서화가 되어 있다면 더욱 좋고요.

친절한 답변 감사합니다 . 😄

2022-08-13 10:41 UTC, ghojeong commented on src/main/java/webserver/http/model/response/ContentType.java
> +
역할이 다르다는 생각이 들면, 저는 우선 분리하는 것을 언제나 권장하는 편입니다.
분리된 것은 나중가서 합치는 것은 크게 어렵지 않은데,
나중에 가서 분리해야한다는 것을 깨닫고 분리하려하면 굉장히 어려워지더라고요.

2022-08-13 10:43 UTC, ghojeong approved these changes
서영수님!
3단계 리팩토링 매우 훌륭하게 진행해주셨습니다!
리팩토링을 하면서 굉장히 많은 고심을 하고 계신게 느껴집니다. 👍 
충분히 깊게 생각을 하신것 같아서 승인 후 머지하겠습니다.

2022-08-13 10:43 UTC, merged