Step2 - HTTP 웹 서버 구현하기
next-step/jwp-was pull request #375
Opened 2022-08-15 05:25 UTC by mincheolkk

안녕하세요 리뷰어님

미션을 수행하고 보니 RequestHandler 클래스 하나에 몽땅 박은 느낌이네요.
궁금한 점이 하나 있는데요. 혹시 RequestHandler 는 어떻게 테스트 코드를 짤 수 있을까요 ?

2022-08-16 02:31 UTC, yongdae requested changes
안녕하세요. 민철님!
2단계 미션을 열심히 진행해주셨네요. 👍 

진행해주신 내용에 대해 몇 가지 의견을 남겨 놓았습니다.
확인하시고 다시 리뷰 요청 부탁드릴께요. 🔥

2022-08-16 02:31 UTC, yongdae commented on README.md
> +## step 2 - HTTP 웹 서버 구현
미션 진행에 앞서 먼저 요구사항을 정리해주셨네요. 💯

2022-08-16 02:31 UTC, yongdae commented on src/test/java/webserver/HttpHeaderTest.java
> +    void 잘되는지_확인() {
메소드의 이름은 영어로 작성하고
조금 더 구체적인 설명은 @DisplayName를 사용해보면 어떨까요?

2022-08-16 02:31 UTC, yongdae commented on src/main/java/webserver/RequestHandler.java
> +    private String setCookie(String bool) {
Cookie에 대한 부분을 하나의 클래스로 분리해볼 수는 없을까요?

2022-08-16 02:31 UTC, yongdae commented on src/main/java/webserver/RequestHandler.java
>      }
MVC 패턴에이서 이야기하는 Controller을 이 부분에 적용해서
HandleBarsTemplate처럼 클래스로 분리해본다면 좋을 것 같아요. :)

2022-08-16 02:31 UTC, yongdae commented on src/main/java/webserver/RequestHandler.java
>  public class RequestHandler implements Runnable {
RequestHandler의 테스트 방법에 대해서 질문해주셨는데요.

앞서 의견 드린 것처럼 클라이언트로 부터의 요청을 처리하는 부분을 컨트롤러로 분리한다면
HandleBarsTemplate처럼 테스트를 만들어 볼 수 있을 것 같아요. 😄

2022-08-16 02:31 UTC, yongdae commented on src/main/java/webserver/HandleBarsTemplate.java
> +public class HandleBarsTemplate {
Template을 이용해 화면을 그리는 부분을 별개의 클래스로 분리해주셨네요. 👍

2022-08-22 16:47 UTC, mincheolkk commented on src/test/java/webserver/HttpHeaderTest.java
> +    void 잘되는지_확인() {
넵!

2022-08-22 16:47 UTC, mincheolkk commented on src/main/java/webserver/RequestHandler.java
> +    private String setCookie(String bool) {
네~ Cookie 클래스 따로 분리해서 리팩토링 진행했습니다~

2022-08-22 16:48 UTC, mincheolkk commented on src/main/java/webserver/RequestHandler.java
>      }
미션3 자료들 참고하면서 Controller 적용했습니다~

2022-08-22 16:48 UTC, mincheolkk commented on src/main/java/webserver/RequestHandler.java
>  public class RequestHandler implements Runnable {
답변 감사합니다 :)

2022-08-22 16:51 UTC, mincheolkk commented
안녕하세요 리뷰어님~ 
피드백 해주신 부분과 미션3 자료 보면서 리팩토링 진행했습니다. 
감사합니다 :)

2022-08-23 08:45 UTC, yongdae approved these changes
힌트를 참고해서 진행해주셨군요.
리팩토링이 진행되어 코드의 구조가 탄탄해졌네요. 👍 

몇 가지 의견 드린 부분은 다음 단계에서 마무리 지으면 될 것 같네요.
수고하셨습니다. 😄

2022-08-23 08:45 UTC, yongdae commented on src/main/java/webserver/Cookie.java
> +public class Cookie {
Cookie를 잘 분리해서 적용해주셨네요. 👍

2022-08-23 08:45 UTC, yongdae commented on src/main/java/webserver/Cookie.java
> +    public static String setLoginCookie(String bool) {
로그인과 관련된 작업이 Cookie에 강한 결합을 가지고 있는 것 같아요. 
Cookie가 로그인 처리에 대해 알아야 할 이유가 있을까요? 🤔

2022-08-23 08:45 UTC, yongdae commented on src/main/java/webserver/HttpRequest.java
> +public class HttpRequest {
💯

2022-08-23 08:45 UTC, yongdae commented on src/main/java/webserver/HttpRequest.java
> +    private Cookie cookie;
멤버 변수의 갯수를 줄일 수 있는 방법을 고민해보면 좋을 것 같아요. :)

2022-08-23 08:45 UTC, yongdae commented on src/main/java/webserver/HttpResponse.java
> +public class HttpResponse {
응답 객체도 잘 분리해주셨네요. 👍 
추가로 HttpResponse에 대한 테스트를 추가해보면 어떨까요?

2022-08-23 08:45 UTC, yongdae commented on src/main/java/webserver/HttpResponse.java
> +    private DataOutputStream dos;
HttpResponse가 가진 멤버 변수의 갯수도 줄일 수 있는 방법을 고민해보면 좋겠어요. :)

2022-08-23 08:45 UTC, yongdae commented on src/main/java/webserver/RequestHandler.java
> +            controller.service(httpRequest, httpResponse);
클라이언트의 요청을 처리하는 로직이 깔끔하게 바뀌었네요. 💯

2022-08-23 08:45 UTC, yongdae commented on src/main/java/controller/LoginController.java
> +public class LoginController extends AbstractController {
LoginController, ListUserController를 사용해서
미션에서 요구한 기능 5, 6번을 검증해보면 좋을 것 같아요!

사용자 혹은 개발자가 화면으로 기능을 테스트 할 수 있지만 코드를 통해 검증 할 수 있다면 보다 더 빠르고 정확하지 않을까요?

2022-08-23 08:45 UTC, yongdae commented on src/main/java/controller/LoginController.java
> +    }
AbstractController에서 정의한 내용을 동일하게 정의하신 이유가 있으신가요?

2022-08-23 08:45 UTC, merged

2022-08-26 03:21 UTC, mincheolkk commented on src/main/java/controller/LoginController.java
> +    }
이 질문을 깜빡하고 답변을 못 했었네요 ㅎㅎ 
음 LoginController 에서는 POST 메서드만 현재 작동을 하는데요. 그렇기에 InvalidHttpMethodException 를 새로 만들어서 GET요청시 설정해둔 ("유효하지 않은 Http Method 입니다.") 문구를 표출해주기위해 LoginController 에서 override 했습니다! :)