🚀 3단계 - HTTP 웹 서버 리팩토링
next-step/jwp-was pull request #388
Opened 2022-08-24 17:55 UTC by younlll

안녕하세요! 3단계 리뷰 요청 드립니다.
처음 피드백 주신 대로 혼자 리팩토링을 해보려다 몇번을 원복하고 다시 구현해본지 모르겠네요.... 😥
결국 NEXTSTEP 3단계에 나와있는 힌트를 참고해서 클래스 분리를 해보았습니다.
여전히 아직 머릿속으로 구현이 떠오르지 않아서 인지 테스트 코드를 먼저 작성하진 못했습니다.
그리고 피드백 내용 중에 요청 경로별로 if else 분기 처리에 대한 것이 있었는데요.
저도 Map을 이용해서 넣으면 될거 같다는 생각은 드는데
아직 구현으로는 어려워 조금 더 시간이 필요할거 같아 우선 PR 올렸습니다...... 😭😭😭

2022-08-25 14:58 UTC, liquidjoo requested changes
3단계 미션 잘 구현해주셨어요 👍 
몇가지 생각해볼 만한 코멘트 남겼어요~
확인하고 다시 요청 주세요 🙇 
궁금한 것이 있으면 언제든 슬랙을 통해 DM 주세요!!

2022-08-25 14:58 UTC, liquidjoo commented on src/main/java/controller/AbstractController.java
> +        ;
불필요한 코드는 삭제하는 것이 좋을 것 같아요~

2022-08-25 14:58 UTC, liquidjoo commented on src/main/java/controller/AbstractController.java
> +        doPost(request, response);
delete, put, patch 와 같은 메서드가 추가된다면 분기를 계속 해야할 것 같은데요~
switch or 다중 if 를 사용하지 않고 어떻게 구현해 볼 수 있을까요?

2022-08-25 14:58 UTC, liquidjoo commented on src/main/java/controller/UserListController.java
> +        response.forward(new ResponseBody(listPage), CONTENT_TYPE);
메서드 분리를 통해서 책임을 분리해보는 것이 어떨까요?

2022-08-25 14:58 UTC, liquidjoo commented on src/main/java/model/HttpHeaders.java
> +        this.header.put("Location", location);
매직넘버
매직 넘버란 코드 안에 작성된 구체적인 숫자 혹은 문자열을 말합니다. 그리고 매직 넘버의 단점은 아래와 같습니다.
- 의미를 이해하기 어렵다.
- 복수의 장소에서 사용된다면 변경하기 힘들다.

그런 매직 넘버는 의미를 나타낼 수 있는 상수로 치환하여 코드의 가독성을 높여 보는 것은 어떨까요?

2022-08-25 14:58 UTC, liquidjoo commented on src/main/java/model/response/HttpResponse.java
> +public class HttpResponse {
빈 생성자를 만들어 메서드를 통해 상태 값을 채운다면 빈약한 객체가 될 수 있는데요~
상태 값을 초기화 할 때 생성자를 활용해보면 어떨까요?
다양한 생성자가 나온다면 팩토리 메서드 패턴을 활용해보는 것도 좋을 것 같아요~
> [참고 링크](https://velog.io/@ljinsk3/%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C%EB%8A%94-%EC%99%9C-%EC%82%AC%EC%9A%A9%ED%95%A0%EA%B9%8C)

2022-08-25 14:58 UTC, liquidjoo commented on src/main/java/webserver/RequestHandler.java
>              if (path.endsWith(".html")) {
다중 if 를 해결해 보면 좋을 것 같아요~
이미 알고 있듯이 Map 을 활용해도 좋고 Interface 를 활용해보아도 좋습니다!!

2022-08-25 14:58 UTC, liquidjoo commented on src/test/java/controller/LoginControllerTest.java
> +}
파일 마지막에 엔터(개행문자)를 넣어주세요!!
이유는 IEEE가 책정한 POSIX에 정의되어 있기 때문인데요~
좀 더 알고 싶으시면 재미삼아 아래의 링크를 보시는 것도 추천 드립니다.
https://velog.io/@doondoony/posix-eol

Intellij 를 사용하실 경우엔
Preferences -> Editor -> General -> Ensure line feed at file end on save 를 체크해주시면
파일 저장 시 마지막에 개행문자를 자동으로 넣어줍니다!

2022-08-25 14:58 UTC, liquidjoo commented on src/main/java/model/HttpHeaders.java
> +        dos.writeBytes("\n");
header 에 대한 키와 값을 StringBuilder or String 을 활용해 한번에 출력할 수 있을 것 같아요!
그럼 dos.writeBytes 를 한번만 호출해도 되고 try-catch도 필요 없이 throws 만 해줘도 될 것 같아요~

2022-08-31 06:36 UTC, younlll commented on src/main/java/webserver/RequestHandler.java
>              if (path.endsWith(".html")) {
interface로 해보고 싶었는데 어렵네요ㅠㅠㅠㅠ

2022-08-31 06:40 UTC, younlll commented on src/main/java/controller/AbstractController.java
> +        doPost(request, response);
여긴 더 고민이 필요할거 같습니다.... 😥

2022-09-01 09:23 UTC, liquidjoo approved these changes
WAS 미션 3단계 피드백 반영 잘하셨어요 👍 
다음 단계 진행해 주세요
고생하셨습니다 🙇

2022-09-01 09:23 UTC, liquidjoo commented on src/main/java/controller/AbstractController.java
> +public abstract class AbstractController implements Controller {
추상 클래스 활용 👍

2022-09-01 09:23 UTC, liquidjoo commented on src/main/java/model/HttpHeaders.java
> +    }
체이닝 메서드 처럼 사용하신점 인상 깊네요 👍

2022-09-01 09:23 UTC, liquidjoo commented on src/main/java/model/response/HttpResponse.java
> +    private ResponseBody responseBody;
responseBody 는 초기화하지 않고 사용이 되고 있는 것 같아요~
의도적인 부분일까요?

2022-09-01 09:23 UTC, merged