Step4
next-step/jwp-was pull request #86
Opened 2019-08-13 11:25 UTC by pplenty

2019-08-13 23:58 UTC, byjo requested changes
세션 구현까지 잘 수행 하셨네요. 👍👍👍
다만 책임이 명확하지 않는 객체가 존재하여 이 부분을 정리하고 마무리 하면 좋을 것 같습니다.
피드백 참고하셔서 SessionManager의 책임이 무엇인지 고민해보시고, 본연의 역할에 맞도록 변경해주세요.
고지가 눈 앞이니 마지막까지 화이팅 하시구요! 👏

2019-08-13 23:58 UTC, byjo commented on src/main/java/webserver/http/common/session/SessionManager.java
> +    public static void setSession(HttpRequest httpRequest) {
SessionManager의 역할은 무엇일까요? 
세션 목록의 관리, 즉 세션을 생성/삭제하거나 적합한 세션을 반환하는 것이 아닐까 싶은데요.

그런데 `setSession()` 메서드로 인해 SessionManager와 HttpRequest간의 관계가 생겼네요. 
HttpRequest가 SessionManager에 sessionId에 해당하는 HttpSession을 요청하는 구조로 변경하는 것이 좋을 것 같습니다.

2019-08-13 23:58 UTC, byjo commented on src/main/java/webserver/http/common/session/SessionManager.java
> +        if (sessionId == null) {
sessionId가 null 이거나 맵에서 가져온 HttpSession이 없는 경우에 대해 아래 구조의 중복이 발생하네요.
```
if (XXX == null) {
   createNewSession();
}
```

이러한 if 분기를 하나로 줄일 수 있는 방법을 함께 고민하시면 좋을 것 같습니다.

2019-08-14 18:13 UTC, pplenty commented on src/main/java/webserver/http/common/session/SessionManager.java
> +    public static void setSession(HttpRequest httpRequest) {
각자의 역할에 충실해야 한다는 것을 다시 한번 깨닫습니다.
request 안에서 manager를 이용해 세션을 얻어오는 로직으로 바꿨다가, 
그렇게 해도 관계가 남아있는 것 같아서 manager 객체를 외부에서 받아 사용하는 것으로 바꿨습니다.

2019-08-14 18:20 UTC, pplenty commented on src/main/java/webserver/http/common/session/SessionManager.java
> +        if (sessionId == null) {
putIfAbsent 을 사용하여 중복을 제거 하였습니다. 다만 한가지 걸리는 것이 남았는데, 기존 map 에 자료가 있던지 없던지 HttpSession 객체를 무조건 생성하는 게 되네요. 다른 방법이 있을까요?

2019-08-15 10:48 UTC, byjo commented on src/main/java/webserver/http/common/session/SessionManager.java
> +        if (sessionId == null) {
처음 코드를 봤을 땐 아래와 같은 방법을 생각했어요.
sessionId가 null이거나 sessionId로 조회한 값이 null 인 것은 valid하지 않은 세션이라 생각하고, isValidSession() 메서드를 만들어 이를 통해 알아오는 것이 좋을 것이라 생각했구요.
```
	public HttpSession get(String sessionId) {	

		if (isValidSession(sessionId)) {
		    return sessions.get(sessionId);
		}

		return create();
	}

	public boolean isValidSession(String sessionId) {
        return sessionId != null && sessions.containsKey(sessionId);
    }
```

---
이번에 putIfAbsent()를 사용하신 걸 보니, 아래와 같은 방법으로도 구현할 수 있지 않을까 싶었습니다.
다만 이 방법의 경우 EMPTY라는 정적 클래스 변수를 둬야 한다는 점(일반적인 Model에서는 자주 사용하지만 HttpSession의 경우에는 사용성이 있을까 싶어서...), 어떤 경우든 map에 두 번의 접근을 한다는 점이 걸리긴 하네요.
```
public HttpSession createSessionIfAbsent(String sessionId) {
    String id = Optional.ofNullable(sessionId).orElse(HttpSession.EMTPY.getId());
    HttpSession session = sessions.getOrDefault(id, new HttpSession());
    sessions.putIfAbsent(session.getId(), session);

    return session;
}
```

2019-08-15 10:55 UTC, byjo approved these changes
피드백 반영하신 것 확인 잘 했습니다. 웹 서버 구현을 마치신 걸 축하드려요. 🎉
이번에 함께 코드를 공유하고 고민해보면서 즐거웠습니다.
제가 즐거웠던 만큼 유식님에게도 의미있는 시간이였기를 바라면서, 
앞으로 남은 미션들도 즐겁게 진행 하시길 바랄게요. 👏

2019-08-15 10:55 UTC, merged